import { useEffect, useState } from 'react'
import { Alert, Button, Col, Form, Modal, Row } from 'react-bootstrap'
import ApiService from '@/services/ApiService'
import { useNotificationContext } from '@/context/useNotificationContext'

const readFileAsBase64 = (file) => new Promise((resolve, reject) => {
  const reader = new FileReader()
  reader.onload = () => resolve(String(reader.result).split(',')[1] || '')
  reader.onerror = reject
  reader.readAsDataURL(file)
})

const EMPTY_FORM = { payment_type_id: '', client_record_id: '', company_name: '', payment_method_id: '', amount: '', settlement_start: '', settlement_end: '', external_reference: '', prepared_by: '', notes: '' }

const WESTERN_UNION_TYPE_ID = '1'

/** Legacy's "Add Manual Payment" modal — same form for both Draft and Submit-for-Verification, only the final `status` sent differs. */
const AddManualPaymentModal = ({ show, onHide, types, methods, clients, onDone }) => {
  const { showNotification } = useNotificationContext()
  const [form, setForm] = useState(EMPTY_FORM)
  const [file, setFile] = useState(null)
  const [fileName, setFileName] = useState('')
  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState('')

  useEffect(() => {
    if (show) {
      setForm(EMPTY_FORM)
      setFile(null)
      setFileName('')
      setError('')
    }
  }, [show])

  const set = (key, value) => setForm((f) => ({ ...f, [key]: value }))

  const handleTypeChange = (value) => {
    setForm((f) => ({
      ...f,
      payment_type_id: value,
      company_name: value === WESTERN_UNION_TYPE_ID && !f.company_name ? 'Western Union International' : f.company_name,
    }))
  }

  const handleCompanyChange = (value) => {
    const match = clients.find((c) => c.company_name.toLowerCase() === value.toLowerCase())
    setForm((f) => ({ ...f, company_name: value, client_record_id: match ? String(match.client_record_id) : '' }))
  }

  const handleFile = async (selected) => {
    if (!selected) {
      setFile(null)
      setFileName('')
      return
    }
    setFileName(selected.name)
    setFile(await readFileAsBase64(selected))
  }

  const submit = async (status) => {
    if (form.settlement_end < form.settlement_start) {
      setError('Settlement Period End must be on or after the Start date.')
      return
    }
    if (!file) {
      setError('A supporting document is required.')
      return
    }
    setSubmitting(status)
    setError('')
    try {
      const result = await ApiService.addPaymentManagement({ ...form, client_record_id: form.client_record_id || null, document: file, document_name: fileName, status })
      showNotification({ title: 'Success', message: result?.message || 'Manual payment saved.', variant: 'success' })
      onDone?.()
      onHide()
    } catch (err) {
      setError(err?.errors ? Object.values(err.errors)[0]?.[0] : (err?.message || 'Unable to save manual payment.'))
    } finally {
      setSubmitting('')
    }
  }

  return (
    <Modal show={show} onHide={onHide} centered size="lg">
      <Modal.Header closeButton>
        <Modal.Title>Add Manual Payment</Modal.Title>
      </Modal.Header>
      <Modal.Body>
        <p className="text-muted small">Use this for payments not automatically generated by a SunCash system.</p>
        {error && <Alert variant="danger" className="py-2 small mb-3">{error}</Alert>}
        <Row className="g-3">
          <Col md={6}>
            <Form.Label>Payment Type *</Form.Label>
            <Form.Select value={form.payment_type_id} onChange={(e) => handleTypeChange(e.target.value)}>
              <option value="">Select payment type</option>
              {types.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}
            </Form.Select>
          </Col>
          <Col md={6}>
            <Form.Label>Company Name *</Form.Label>
            <Form.Control list="pm-clients" autoComplete="off" value={form.company_name} onChange={(e) => handleCompanyChange(e.target.value)} placeholder="Type a company name" />
            <datalist id="pm-clients">
              {clients.map((c) => <option key={c.client_record_id} value={c.company_name} />)}
            </datalist>
          </Col>
          <Col md={6}>
            <Form.Label>Payment Method *</Form.Label>
            <Form.Select value={form.payment_method_id} onChange={(e) => set('payment_method_id', e.target.value)}>
              <option value="">Select payment method</option>
              {methods.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}
            </Form.Select>
          </Col>
          <Col md={6}>
            <Form.Label>Amount *</Form.Label>
            <Form.Control type="number" min="0.01" step="0.01" value={form.amount} onChange={(e) => set('amount', e.target.value)} placeholder="0.00" />
          </Col>
          <Col md={6}>
            <Form.Label>Settlement Period Start *</Form.Label>
            <Form.Control type="date" value={form.settlement_start} onChange={(e) => set('settlement_start', e.target.value)} />
          </Col>
          <Col md={6}>
            <Form.Label>Settlement Period End *</Form.Label>
            <Form.Control type="date" value={form.settlement_end} onChange={(e) => set('settlement_end', e.target.value)} />
          </Col>
          <Col md={6}>
            <Form.Label>External Report / Reference No.</Form.Label>
            <Form.Control value={form.external_reference} onChange={(e) => set('external_reference', e.target.value)} placeholder="e.g. WU-2026-07-10-01" />
          </Col>
          <Col md={6}>
            <Form.Label>Prepared By *</Form.Label>
            <Form.Control value={form.prepared_by} onChange={(e) => set('prepared_by', e.target.value)} placeholder="Name of person entering payment" />
          </Col>
          <Col md={12}>
            <Form.Label>Supporting Report *</Form.Label>
            <Form.Control type="file" accept=".pdf,.xlsx,.xls,.csv,.doc,.docx,image/*" onChange={(e) => handleFile(e.target.files?.[0] || null)} />
            <Form.Text className="text-muted">Upload the settlement report or other supporting document.</Form.Text>
          </Col>
          <Col md={12}>
            <Form.Label>Notes</Form.Label>
            <Form.Control as="textarea" rows={2} value={form.notes} onChange={(e) => set('notes', e.target.value)} placeholder="Add settlement details, exceptions or instructions." />
          </Col>
        </Row>
      </Modal.Body>
      <Modal.Footer>
        <Button variant="secondary" onClick={onHide} disabled={!!submitting}>Cancel</Button>
        <Button variant="outline-primary" onClick={() => submit('DRAFT')} disabled={!!submitting}>{submitting === 'DRAFT' ? 'Saving...' : 'Save as Draft'}</Button>
        <Button variant="primary" onClick={() => submit('PENDING')} disabled={!!submitting}>{submitting === 'PENDING' ? 'Submitting...' : 'Submit for Verification'}</Button>
      </Modal.Footer>
    </Modal>
  )
}

export default AddManualPaymentModal
